--- 
title: "Tidyverse 食谱"
subtitle: "实战案例集合"
author: "黄湘云"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
papersize: b5
fontsize: 10pt
graphics: yes
colorlinks: yes
mathspec: yes
lot: yes
lof: yes
geometry:
  - tmargin=2.5cm
  - bmargin=2.5cm
  - lmargin=3.0cm
  - rmargin=2.0cm
classoption: "UTF8,twoside,openany,table"
bibliography: 
  - book.bib
  - packages.bib
biblio-style: plainnat
natbiboptions: "authoryear,round"
link-citations: yes
description: "tidyverse 实战经验总结."
github-repo: XiangyunHuang/tidyverse-cookbook
# cover-image: ""
---

\mainmatter

```{r setup,include=FALSE}
library(reticulate)
knitr::opts_chunk$set(tidy = TRUE)
knitr::opts_chunk$set(
  python.reticulate = TRUE,
  pdfcrop = knitr::hook_pdfcrop
)
if(!is.na(Sys.getenv('CI', NA))) {
  # Remote macOS CI 环境
  reticulate::use_condaenv("r-reticulate", required = TRUE)
} else {
  # Local macOS 环境
  use_python(python = '/usr/local/bin/python3', required = TRUE)
}
```

# 欢迎 {#welcome .unnumbered}
\chaptermark{欢迎}

::: {.rmdwarn data-latex="{警告}"}
Book in early development. Planned release in 202X. 
:::

::: {.flushright data-latex=""}
黄湘云  
北京, 北京
:::

## 软件信息 {#session .unnumbered}
\index{xfun}

```{r}
xfun::session_info(packages = c(
  "knitr", "rmarkdown", "bookdown"
), dependencies = TRUE)
```



```{r include=FALSE,cache=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
